In [1]:
import random , csv
from pprint import pprint
import pandas as pd

class BMI(): 
    def __init__(self,name:str,height:int,weight:int): 
        self.name = name
        self.height = height
        self.weight = weight

    def get_bmi(self)->float: #取得bmi
        return round(self.weight / (self.height/100) ** 2,ndigits=2)
    
    def get_status(self)->str:  #取得status
        bmi = self.get_bmi()
        if bmi >=35:
            status = "重度肥胖"
        elif bmi >= 30:
            status = "中度肥胖"
        elif bmi >= 27:
            status = "輕度肥胖"
        elif bmi >= 24:
            status = "過重"
        elif bmi >= 18.5:
            status = "正常範圍"
        else:
            status = "體重過輕"
        return status

def get_name(nums:int=2)->list[str]: #抓取name.txt裡面的名字
    with open('names.txt',mode='r',encoding='utf-8') as file:
            names_str = file.read()
    names = names_str.split()
    names = random.choices(names,k=nums)
    return  names
     
def generate_bmi(names:list[str])->list[BMI]: 
    students:list[BMI] = []
    for name in names:
        height = random.randint(140,190)
        weight = random.randint(50,110)
        student_STATUS = BMI(name, height, weight)
        students.append(student_STATUS) #list實體化 
    return students

if __name__ == '__main__':
    nums = int(input('請輸入人數:'))
    names:list[str] = get_name(nums=nums)
    students:list[BMI] = generate_bmi(names=names)
    file_dict:list[dict] = []
    for student in students:
        #將資料轉換成字典
        student_dict = {
        "姓名": student.name,
        "身高": student.height,
        "體重": student.weight,
        "BMI": student.get_bmi(),
        "狀態": student.get_status()
        }
        file_dict.append(student_dict)  #寫入list[dict]
    
pprint(file_dict)#測試
df = pd.DataFrame(file_dict, 
                       columns=['姓名', '身高', '體重', 'BMI', '狀態'], #依據欄位名稱重新排序
                       index= range(1,nums+1)) #設定索引從1~nums(包含nums)
df.index.name = '學號'
df

[{'BMI': 39.08, '姓名': '楊火帆', '狀態': '重度肥胖', '身高': 167, '體重': 109},
 {'BMI': 38.29, '姓名': '龔姵君', '狀態': '重度肥胖', '身高': 149, '體重': 85},
 {'BMI': 28.08, '姓名': '柯韋成', '狀態': '輕度肥胖', '身高': 182, '體重': 93},
 {'BMI': 39.9, '姓名': '白世宏', '狀態': '重度肥胖', '身高': 163, '體重': 106},
 {'BMI': 29.22, '姓名': '錢佩豪', '狀態': '輕度肥胖', '身高': 148, '體重': 64}]

     姓名   身高   體重    BMI    狀態
學號
1   楊火帆  167  109  39.08  重度肥胖
2   龔姵君  149   85  38.29  重度肥胖
3   柯韋成  182   93  28.08  輕度肥胖
4   白世宏  163  106  39.90  重度肥胖
5   錢佩豪  148   64  29.22  輕度肥胖

In [3]:
sdata = {'台北':[35000,60000,75000],'桃園':[52000,40000,2000],'台中':[33000,11100,35000],'高雄':[5000,6000,7500]}
pprint(sdata)

{'台中': [33000, 11100, 35000],
 '台北': [35000, 60000, 75000],
 '桃園': [52000, 40000, 2000],
 '高雄': [5000, 6000, 7500]}

In [4]:
df2 = pd.DataFrame(sdata)
df2

      台北     桃園     台中    高雄
0  35000  52000  33000  5000
1  60000  40000  11100  6000
2  75000   2000  35000  7500