In [47]:
import pandas as pd

df1 = pd.read_csv('111各鄉鎮市區人口密度.csv')
df1

,statistic_yyy,site_id,people_total,area,population_density
0,統計年,區域別,年底人口數,土地面積,人口密度
1,111,新北市板橋區,549572,23.1373,23753
2,111,新北市三重區,379825,16.317,23278
3,111,新北市中和區,403109,20.144,20011
4,111,新北市永和區,212170,5.7138,37133
...,...,...,...,...,...
370,111,南沙群島,…,0.5045,…
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN

In [48]:
#使用info()檢查dataFrame
df1.info()  #查出來的Dtype=object代表是字串

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   statistic_yyy       371 non-null    object
 1   site_id             374 non-null    object
 2   people_total        371 non-null    object
 3   area                371 non-null    object
 4   population_density  371 non-null    object
dtypes: object(5)
memory usage: 14.8+ KB

In [49]:
#實體方法rename()->改變欄位名稱
df2 = df1.rename(columns={
    'statistic_yyy':'統計年',
    'site_id':'區域別',
    'people_total':'年底人口數',
    'area':'土地面積',
    'population_density':'人口密度'
    })
df2

,統計年,區域別,年底人口數,土地面積,人口密度
0,統計年,區域別,年底人口數,土地面積,人口密度
1,111,新北市板橋區,549572,23.1373,23753
2,111,新北市三重區,379825,16.317,23278
3,111,新北市中和區,403109,20.144,20011
4,111,新北市永和區,212170,5.7138,37133
...,...,...,...,...,...
370,111,南沙群島,…,0.5045,…
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN

In [50]:
#Drop()   DataFrame.drop(labels=None, *, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')
df3 = df2.drop(index=0)
df3

,統計年,區域別,年底人口數,土地面積,人口密度
1,111,新北市板橋區,549572,23.1373,23753
2,111,新北市三重區,379825,16.317,23278
3,111,新北市中和區,403109,20.144,20011
4,111,新北市永和區,212170,5.7138,37133
5,111,新北市新莊區,419966,19.7383,21277
...,...,...,...,...,...
370,111,南沙群島,…,0.5045,…
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN

In [51]:
#dropna     DataFrame.dropna(*, axis=0, how=<no_default>, thresh=<no_default>, subset=None, inplace=False, ignore_index=False)
df4 = df3.dropna()
df4

     統計年     區域別   年底人口數     土地面積    人口密度
1    111  新北市板橋區  549572  23.1373  23753
2    111  新北市三重區  379825   16.317  23278
3    111  新北市中和區  403109   20.144  20011
4    111  新北市永和區  212170   5.7138  37133
5    111  新北市新莊區  419966  19.7383  21277
..   ...     ...     ...      ...     ...
366  111  連江縣北竿鄉    3181      9.9    321
367  111  連江縣莒光鄉    1471      4.7    313
368  111  連江縣東引鄉    1534      3.8    404
369  111    東沙群島      …      2.38      …
370  111    南沙群島      …    0.5045      …

[370 rows x 5 columns]

In [52]:
#DataFrame.replace(to_replace=None, value=<no_default>, *, inplace=False, limit=None, regex=False, method=<no_default>)
df4[-5:].values
df5 = df4.replace('… ',value=0)
df5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 370 entries, 1 to 370
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   統計年     370 non-null    object
 1   區域別     370 non-null    object
 2   年底人口數   370 non-null    object
 3   土地面積    370 non-null    object
 4   人口密度    370 non-null    object
dtypes: object(5)
memory usage: 17.3+ KB

In [53]:
#DataFrame.astype(dtype, copy=None, errors='raise')
df6 = df5.astype({
    '年底人口數':'int',
    '人口密度':'int',
    '土地面積':'float'
})
df6.info()

<class 'pandas.core.frame.DataFrame'>
Index: 370 entries, 1 to 370
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   統計年     370 non-null    object
 1   區域別     370 non-null    object
 2   年底人口數   370 non-null    int64
 3   土地面積    370 non-null    float64
 4   人口密度    370 non-null    int64
dtypes: float64(1), int64(2), object(2)
memory usage: 17.3+ KB

In [54]:
#不會使用for in迴圈,因為不會得到索引編號
for value in df5['年底人口數']:
    #print(type(value))
    print(value)

549572
379825
403109
212170
419966
298594
180067
88406
115274
187823
206265
37695
237538
199811
91436
76982
127887
23528
7292
6553
22228
10961
40902
4268
8102
11260
20577
21101
6359
189939
203780
284557
212669
148103
118833
173040
257558
113798
272963
264716
240725
462338
423722
94313
177602
167205
85991
172274
209952
124973
227810
49205
73026
13053
17635
75554
125466
112278
142778
231866
177930
295677
163476
47817
74737
88947
97002
59848
53667
64308
108639
95275
23283
14154
31264
18230
78122
56129
77887
64091
196011
211469
10919
74908
24452
26203
20407
21891
19366
42933
22635
21342
20849
8847
58063
24749
24713
21439
18618
10183
42467
51842
37482
29904
6976
13118
8870
8114
4366
76896
68044
33424
3601
234130
180511
121035
126068
199118
68025
77408
22481
139590
195296
191313
330419
49068
26633
162642
180282
26671
154808
356016
68429
111514
40732
33670
95089
44168
95349
40470
28963
6655
27656
50602
29540
29480
13776
18468
34845
34622
37317
11920
5661
11094
13499
1940
4258
3201
94679
70012
37867
28453
34800
24417
31918
52761
40662
21235
6139
6119
209221
27099
33055
96375
81232
12212
58651
20159
14391
8672
5319
9574
4543
86112
105354
43927
31835
88364
34358
15514
13219
31445
16682
9046
9948
15151
6440
11706
6143
4149
5739
226519
122367
85370
88666
33259
54056
39693
48390
16303
37948
45445
38258
44296
22456
40392
31349
33813
35464
41606
14168
26069
29293
31614
15455
14370
28620
97361
77244
96646
51863
10068
36234
16477
13841
14892
17256
16387
15594
15732
107791
43355
70305
44578
27650
37849
30138
18231
27554
16930
25220
23098
49354
13642
12143
22151
23713
21582
25566
23242
38919
40882
25056
29744
70298
13463
30302
21331
23144
16994
14426
47912
43048
33792
18052
10938
4476
5381
193941
53124
45908
29899
49457
29126
10592
21645
25685
24266
23182
19478
52258
16073
9623
22969
33091
15168
16762
10049
18095
12216
8194
7454
5128
7793
3324
6796
5338
7423
4889
4891
4866
103252
13212
8165
16846
5635
10744
8060
6733
7314
7995
4285
3630
4222
3482
3713
5263
99558
10536
22408
20256
82795
17133
12015
4315
10968
9689
16992
6175
6052
63657
15820
10047
8341
5448
3910
50574
53003
38320
41328
45038
80297
52966
221657
152118
78698
117826
145098
42342
30636
20673
34325
12649
670
7797
3181
1471
1534
0
0

In [55]:
#map
def to_int(value:str)->int:
    try:
        #print(type(value))
        #print(value)
        return int(value)   #轉成series
    except:
        return 0
df5['年底人口數'] = df5['年底人口數'].map(to_int)

In [56]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 370 entries, 1 to 370
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   統計年     370 non-null    object
 1   區域別     370 non-null    object
 2   年底人口數   370 non-null    int64
 3   土地面積    370 non-null    object
 4   人口密度    370 non-null    object
dtypes: int64(1), object(4)
memory usage: 17.3+ KB

In [57]:
df6 = df5.astype({'土地面積':'float','人口密度':'int'})
df6.info()

<class 'pandas.core.frame.DataFrame'>
Index: 370 entries, 1 to 370
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   統計年     370 non-null    object
 1   區域別     370 non-null    object
 2   年底人口數   370 non-null    int64
 3   土地面積    370 non-null    float64
 4   人口密度    370 non-null    int64
dtypes: float64(1), int64(2), object(2)
memory usage: 17.3+ KB

In [58]:
df6

     統計年     區域別   年底人口數     土地面積   人口密度
1    111  新北市板橋區  549572  23.1373  23753
2    111  新北市三重區  379825  16.3170  23278
3    111  新北市中和區  403109  20.1440  20011
4    111  新北市永和區  212170   5.7138  37133
5    111  新北市新莊區  419966  19.7383  21277
..   ...     ...     ...      ...    ...
366  111  連江縣北竿鄉    3181   9.9000    321
367  111  連江縣莒光鄉    1471   4.7000    313
368  111  連江縣東引鄉    1534   3.8000    404
369  111    東沙群島       0   2.3800      0
370  111    南沙群島       0   0.5045      0

[370 rows x 5 columns]

In [66]:
#儲存成為csv檔
df6.to_csv('111各鄉鎮市區人口密度new.csv',index=False)

In [60]:
#儲存成為ecxel檔
df6.to_excel('111各鄉鎮市區人口密度new.xlsx')

In [63]:
#儲存成為json檔
df6.to_json('111各鄉鎮市區人口密度new.json',orient='records',force_ascii=False)